# Generated by Django 5.0.3 on 2024-05-31 09:37

import django.db.models.deletion
import shortuuid.django_fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0002_remove_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "account_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "account_number",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=22,
                        max_length=25,
                        prefix="420",
                        unique=True,
                    ),
                ),
                (
                    "account_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="1234567890",
                        length=22,
                        max_length=22,
                        prefix="",
                        unique=True,
                    ),
                ),
                (
                    "read_code",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="asdcxvfgbhre1234567890",
                        length=22,
                        max_length=22,
                        prefix="",
                        unique=True,
                    ),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[("in-active", "In-Active"), ("active", "Active")],
                        default="in-active",
                        max_length=110,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("kyc_submitted", models.BooleanField(default=False)),
                ("kyc_confirm", models.BooleanField(default=False)),
                (
                    "recommended_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
