# Generated by Django 5.1.5 on 2025-01-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_kycmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycmodel',
            name='identity_image',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/images'),
        ),
        migrations.AlterField(
            model_name='kycmodel',
            name='identity_id',
            field=models.CharField(choices=[('national_id', 'National ID'), ('internation_passport', 'Internation passport')], max_length=100),
        ),
    ]
