# Generated by Django 5.0.3 on 2024-05-31 11:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_useraccount_recommended_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="KYCModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("images", models.ImageField(upload_to="kyc/")),
                (
                    "marrital_status",
                    models.CharField(
                        choices=[
                            ("married", "Married"),
                            ("Single", "Single"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Femail", "Femail"),
                            ("Male", "Male"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "identity_id",
                    models.CharField(
                        choices=[
                            ("national_id", "National ID"),
                            ("internation_password", "Internation Password"),
                        ],
                        max_length=100,
                    ),
                ),
                ("date_of_birth", models.DateTimeField()),
                ("signature", models.ImageField(upload_to="key/signature")),
                ("country", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=10)),
                ("mobile", models.CharField(max_length=255)),
                ("facebook", models.URLField(max_length=255)),
                ("twitter", models.URLField(max_length=255)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
